#!/usr/bin/php
<?php
require_once 'core/probe.php';
require_once 'core/probe/cli.php';
require_once 'core/probe/command/help.php';
require_once 'core/probe/command/create.php';

use Psyche\Core\Probe;
use Psyche\Core\Probe\Command;

$vars = $argv;
unset($vars[0]);

$command = $vars[1];
unset($vars[1]);

$vars = array_values($vars);

switch ($command)
{
	case 'help':
		Command\Help::exec();
		break;
	case 'create':
		Command\Create::exec($vars);
		break;

}

echo PHP_EOL;
exit(0);